export interface Indicators {
  internetUsage?: number;
  electricityAccess?: number;
  basicWaterService?: number;
  basicSanitationService?: number;
  literacyRate?: number;
  infantMortality?: number;
  lifeExpectancy?: number;
  birthRate?: number;
  growthRate?: number;
  urbanPercent?: number;
  ruralPercent?: number;
  malePercent?: number;
  femalePercent?: number;
  elderlyPercent?: number;
  gdp?: number;
  gdpPerCapita?: number;
  inflationRate?: number;
  exports?: number;
  imports?: number;
  workingAgePopulation?: number;
  totalLaborForce?: number;
  unemploymentRate?: number;
  giniIndex?: number;
  homicideRate?: number;
  agriculturalLandPercent?: number;
  forestAreaPercent?: number;
  HDI?: number;
} 